environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      configuration: Release
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      configuration: ReleaseLinux

platform: Any CPU

before_build:
  - dotnet restore AmbermoonTools/AmbermoonTools.sln --verbosity normal

build:
  parallel: true
  project: AmbermoonTools/AmbermoonTools.sln

artifacts:
  - path: AmbermoonTools-Windows-Native.zip
    name: AmbermoonTools-Windows-Native
  - path: AmbermoonTools-Windows32Bit-Native.zip
    name: AmbermoonTools-Windows32Bit-Native
  - path: AmbermoonTools-Linux-Native.tar.gz
    name: AmbermoonTools-Linux-Native

after_build:
  - ps: ./AmbermoonTools/publish.ps1

test: off

deploy:
  - provider: GitHub
    name: AmbermoonTools-Windows-Native
    artifact: AmbermoonTools-Windows-Native
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
      secure: CP6qsCjIlyJrYsuHs4tzdrYUWOO83Jlx6/U0Gqtl/SicGmBaN1hrYUEk6RSL6D8j
    draft: true
    prerelease: false
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
  - provider: GitHub
    name: AmbermoonTools-Windows32Bit-Native
    artifact: AmbermoonTools-Windows32Bit-Native
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
      secure: CP6qsCjIlyJrYsuHs4tzdrYUWOO83Jlx6/U0Gqtl/SicGmBaN1hrYUEk6RSL6D8j
    draft: true
    prerelease: false
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
  - provider: GitHub
    name: AmbermoonTools-Linux-Native
    artifact: AmbermoonTools-Linux-Native
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
      secure: CP6qsCjIlyJrYsuHs4tzdrYUWOO83Jlx6/U0Gqtl/SicGmBaN1hrYUEk6RSL6D8j
    draft: true
    prerelease: false
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
