environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      configuration: ReleaseLinux

platform: Any CPU

before_build:
  - dotnet restore AmbermoonTools/AmbermoonTools.sln --verbosity normal

build:
  parallel: true
  project: AmbermoonTools/AmbermoonTools.sln

artifacts:
  - path: AmbermoonTools-Windows.zip
    name: AmbermoonTools-Windows
  - path: AmbermoonTools-Windows32Bit.zip
    name: AmbermoonTools-Windows32Bit
  - path: AmbermoonTools-Linux.tar.gz
    name: AmbermoonTools-Linux

after_build:
  - ps: ./AmbermoonTools/publish.ps1

test: off

deploy:
  - provider: GitHub
    name: AmbermoonTools-Windows
    artifact: AmbermoonTools-Windows
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
      secure: ku89dMTVkz+PE5bvxWQCLG9PbNTa9tQUsidZ/7726rLEZjIAvDcxEC668Ix9zYmw
    draft: true
    prerelease: false
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
  - provider: GitHub
    name: AmbermoonTools-Windows32Bit
    artifact: AmbermoonTools-Windows32Bit
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
      secure: ku89dMTVkz+PE5bvxWQCLG9PbNTa9tQUsidZ/7726rLEZjIAvDcxEC668Ix9zYmw
    draft: true
    prerelease: false
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
  - provider: GitHub
    name: AmbermoonTools-Linux
    artifact: AmbermoonTools-Linux
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
      secure: ku89dMTVkz+PE5bvxWQCLG9PbNTa9tQUsidZ/7726rLEZjIAvDcxEC668Ix9zYmw
    draft: true
    prerelease: false
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
