namespace Ambermoon.Data.Legacy.ExecutableData;

using System;

/// The texts of the user interface (UITexts.cs). Placeholders in the texts are numbers starting with 0 ("0", "01",
/// "012", ...): the number of digits is the width of the value; they become "{0:00}" and so on.
enum UITextIndex : int32
{
    APR,
    He,
    She,
    His,
    Her,
    Skills,
    Attributes,
    Languages,
    Conditions,
    Male,
    Female,
    /// This contains all of them starting with W (West) and going
    /// clock-wise until W again and then additional N-W and N again.
    /// I guess it is used for the compass which can scroll and display
    /// 3 directions partially at once.
    CardinalDirections,
    /// Contains a 3-digit placeholder for the age.
    AgeDisplay,
    /// Use for things like 50%/80% (e.g. skill values).
    /// Contains 2 2-digit placeholders.
    PercentageValueDisplay,
    /// Use for things like 50/80 (e.g. attribute values).
    /// Contains 2 2-digit placeholders.
    ValueDisplay,
    /// Just the text "EP".
    EP,
    /// Contains a 10-digit placeholder for the EP value.
    EPDisplay,
    /// Contains 2 3-digit placeholders.
    LPDisplay,
    /// Contains 2 3-digit placeholders.
    SPDisplay,
    /// Contains a 3-digit placeholder.
    SLPDisplay,
    /// Contains a 3-digit placeholder.
    TPDisplay,
    /// Contains a 5-digit placeholder for gold and a 4-digit placeholder for food.
    GoldAndFoodDisplay,
    /// A colon followed by a 3-digit placeholder.
    LabeledValueDisplay,
    Gold,
    Food,
    ClassHeader,
    Sex,
    BothSexes,
    /// Contains a 5-digit placeholder.
    WeightGramDisplay,
    /// Number of hands.
    /// Contains a 1-digit placeholder.
    HandsDisplay,
    /// Number of fingers.
    /// Contains a 1-digit placeholder.
    FingersDisplay,
    /// Contains a 3-digit placeholder.
    DamageDisplay,
    /// Contains a 3-digit placeholder.
    DefenseDisplay,
    /// Contains a 3-digit placeholder.
    MaxLPDisplay,
    /// Contains a 3-digit placeholder.
    MaxSPDisplay,
    /// I assume M-B-W stands for "Magische Barriere Waffenlevel"
    /// which means "Magic barrier weapon level" in english.
    /// It's a level of a magic protection penetration.
    /// If the M-B-W value is smaller than the target's M-B-R
    /// value, no damage can be dealt.
    /// Contains a 2-digit placeholder.
    MBWDisplay,
    /// I assume M-B-R stands for "Magische Barriere Rüstungslevel"
    /// which means "Magic barrier armor level" in english.
    /// It's a level of a magic protection. If the
    /// M-B-W value is smaller than the targets M-B-R
    /// value, no damage can be dealt.
    /// Contains a 2-digit placeholder.
    MBRDisplay,
    Attribute,
    Skill,
    Placeholder2Digit,
    Placeholder2DigitInParentheses,
    Cursed,
    Weight,
    /// Contains 2 3-digit placeholders.
    WeightKilogramDisplay,
    Legend,
    Location,
    On,
    Off,
    DataHeader,
    ChooseCharacter,
    Inventory
}

/// The messages of the game (Messages.Index of Messages.cs).
enum MessageIndex : int32
{
    None,
    IOErrorOccured,
    InsertDisk,
    InsertSaveDisk,
    TextBlockMissing,
    DeactivateMusicLackOfMem,
    RestartOutOfMem,
    DontForgetItems = 18,
    Comma,
    FullStop,
    HasNoMoreFood,
    RegainsLP,
    RegainsLPAndSP,
    HasAged,
    HasDiedOfAge,
    AgreeOnPrice,
    AgreeOnFoodPrice,
    HasReachedLevel,
    AttacksWith,
    Attacks,
    WasBroken,
    DidPointsOfDamage,
    ReceiveExp,
    CastsSpell,
    CastsSpellFrom,
    IsNotTheRightAnswer,
    That,
    NothingToRespond, // = 38, in original code this is the first message so subtract 38 and you have the message id there
    OSOutOfMemory,
    FileInUse,
    FileAlreadyExists,
    DirectoryNotFound,
    FileNotFound,
    FileTooLarge,
    InvalidFilename,
    ObjectNotOfRequiredType,
    DiskNotValidated,
    Empty,
    SeekError,
    DiskFull,
    IncompleteRead,
    FileIsWriteProtected,
    FileIsReadProtected,
    NotADosDisk,
    IncompleteWrite,
    EnterBattlePositions,
    WhichScrollToRead,
    ThatsNotASpellScroll,
    CantLearnSpellsOfType,
    ManagedToLearnSpell,
    FailedToLearnSpell,
    PartyRestsFor8Hours,
    NotEnoughSpellLearningPoints,
    NotEnoughSP,
    WrongArea,
    WhichItemToDrop,
    YouNeedThisItem,
    WhichItemToUse,
    WhichItemToExamine,
    DropHowMuchGold,
    DropHowMuchFood,
    ThisCannotBeEquipped,
    WrongClassToEquip,
    WrongSexToEquip,
    NotEnoughFreeHands,
    NotEnoughFreeFingers,
    RestingTooDangerous,
    DropHowMany,
    CannotUseMagicDiscHere,
    ThisItemIsCursed,
    ThisItemFulfillsSpecialPurpose,
    WhomGiveItTo,
    CannotEquipInCombat,
    BlowsTheFlute,
    ReallyDropIt,
    SameItemAlreadyInUse,
    ReallyDropGold,
    ReallyDropFood,
    DarkDontFindWayBack,
    GiveHowMuchGold,
    GiveHowMuchFood,
    TakeHowMany,
    WhereToMoveItTo,
    CannotUnequipInCombat,
    ReviveMessage,
    SeeRoundDiskInFloor,
    YouNoticeATrap,
    ReallyQuit,
    AlreadyKnowsSpell,
    CannotUseBrokenItems,
    CannotUseItHere,
    YouLevitate,
    WhichNumber,
    CannotJumpThroughWalls,
    WhichMemberShouldBeBlinked,
    HasOpenedDoor,
    HearStrangeSound,
    HasUnlockedDoor,
    DiscoverTrap,
    DoesNotDiscoverTraps,
    DisarmTrap,
    UnlockedDoorWithLockpick,
    LockpickBreaks,
    UnableToPickTheLock,
    WhichItemToOpenDoor,
    WhichItemToOpenChest,
    HasUnlockedChest,
    HasOpenedChest,
    UnlockedChestWithLockpick,
    ThisItemDoesNotOpenDoor,
    ThisItemDoesNotOpenChest,
    WhichItemToPutInChest,
    StoreHowMany,
    StoreHowMuchGold,
    StoreHowMuchFood,
    NoMoreGoldFitsIntoChest,
    NoMoreFoodFitsIntoChest,
    NoOneCanCarryThatMuch,
    ChestFull,
    ChestNowFull,
    ReadWriteError,
    ReallyLoad,
    ReallyOverwriteSave,
    SaveWhichSavegame,
    DenyLeavingPartyOnMoon,
    CannotSendDeadPeopleAway,
    CrazyPeopleDontFollowCommands,
    PetrifiedPeopleCantGoHome,
    SleepUntilDawn,
    HowAboutSomeMore,
    WhoToTalkTo,
    SelfTalkingIsMad,
    ThisPersonIsAsleep,
    YouDontSpeakSameLanguage,
    DontKnowAnythingSpecialAboutIt,
    WhichItemToShow,
    WhichItemToGive,
    GiveHowMuchGoldToNPC,
    GiveHowMuchFoodToNPC,
    NotInterestedInGold,
    NotInterestedInFood,
    NotInterestedInItem,
    DenyJoiningParty,
    WellShouldLeave,
    Hello,
    GoodBye,
    YesWhatIsIt,
    YouCantConversate,
    PartyFull,
    WelcomeCriticalHitTrainer,
    WelcomeHealer,
    WelcomeSage,
    WelcomeRecharger,
    WelcomeInnkeeper,
    WelcomeMerchant,
    WelcomeFoodDealer,
    WelcomeMagician,
    WelcomeRaftSeller,
    WelcomeShipSeller,
    WelcomeHorseSeller,
    LootAfterBattle,
    NoOneReceivesExp,
    WhichItemToSell,
    SellHowMany,
    WayBackTooDangerous,
    PleaseRemoveWriteProtection,
    CannotCarryAllGold,
    ForThisIllGiveYou,
    ReallyWantToGoThere,
    Flees,
    AlreadyAtGotoPoint,
    GotoPointSaved,
    CannotBuyAnymore,
    WhichItemToBuy,
    BuyHowMany,
    ThisWillCost,
    WhichMerchantItemToExamine,
    NotEnoughMoney,
    StayWillCost,
    PriceForRaft,
    PriceForShip,
    PriceForHorse,
    WhichItemToEnchant,
    MoveHowMuchFood,
    BuyHowMuchFood,
    PriceOfFood,
    FoodLeftAfterDividing,
    FoodDividedEqually,
    WantToLeaveRestOfFood,
    LeaveBoughtGoods,
    CannotEnchantOrdinaryItem,
    AlreadyFullyCharged,
    CannotRechargeAnymore,
    PriceForEnchanting,
    LastTimeEnchanting,
    HowManyCharges,
    WhichItemToExamineSage,
    ItemAlreadyIdentified,
    PriceForExamining,
    HowManyLP,
    PriceForHealing,
    WhichConditionToHeal,
    CompletelyExhausted,
    RestingWouldHaveNoEffect,
    PriceForHealingCondition,
    PriceForRemovingCurses,
    TrainHowOften,
    PriceForTraining,
    NotEnoughTrainingPoints,
    IncreasedAfterTraining,
    WelcomeAttackTrainer,
    WelcomeParryTrainer,
    WelcomeSwimTrainer,
    WelcomeFindTrapTrainer,
    WelcomeDisarmTrapTrainer,
    WelcomeLockPickingTrainer,
    WelcomeSearchTrainer,
    WelcomeReadMagicTrainer,
    WelcomeUseMagicTrainer,
    Empty1,
    LPAreNow,
    SPAreNow,
    SLPAreNow,
    TPAreNow,
    APRAreNow,
    NextLevelAt,
    MaxLevelReached,
    AttackWantToFight,
    WhereToMoveTo,
    NowhereToMoveTo,
    CouldNotEscape,
    NoAmmunition,
    WhatToAttack,
    CannotReachAnyone,
    ItemIsBroken,
    WelcomeBlacksmith,
    WhichItemToRepair,
    WontBuyBrokenStuff,
    MissedTheTarget,
    CannotPenetrateMagicalAura,
    AttackFailed,
    AttackWasDeflected,
    AttackDidNoDamage,
    MadeCriticalHit,
    UsedLastAmmunition,
    CannotMove,
    TooFarAway,
    UnableToAttack,
    SomeoneAlreadyGoingThere,
    SelectNewLeader,
    Empty2,
    GettingTired,
    WaitHowManyHours,
    MonstersAdvance,
    MoreFoodWouldBeGood,
    Moves,
    WayWasBlocked,
    LoadWhichSavegame,
    HasDroppedWeapon,
    Retreats,
    PartyAdvances,
    Options,
    WhichPartyMemberAsTarget,
    WhichMonsterAsTarget,
    WhichInventoryAsTarget,
    WhichPartyMemberRowAsTarget,
    WhichMonsterRowAsTarget,
    WhichItemAsTarget,
    WrongWorld,
    SpellFailed,
    WrongClassToUseItem,
    WrongPlaceToUseItem,
    WrongWorldToUseItem,
    DeflectedSpell,
    ImmuneToSpellType,
    TheSpellFailed,
    IsNotDead,
    CannotBeResurrected,
    IsNotAsh,
    IsNotDust,
    AshesChangedToBody,
    DustChangedToAshes,
    AshesFallToDust,
    BodyBurnsUp,
    ItemAlreadyFullyCharged,
    UseSpellOnlyInCitiesOrDungeons,
    MarksPosition,
    ReturnToMarkedPosition,
    HasntMarkedAPosition,
    CannotDamagePetrifiedMonsters,
    ImmuneToSpell,
    ThisIsNotAMagicalItem,
    NoChargesLeft,
    WhereToBlinkTo,
    HasBlinked,
    CannotBlink,
    CannotBeDuplicated,
    CannotClimbHere,
    ItemIsNotBroken,
    NoRoomForItem,
    NoCursedItemFound,
    CannotRepairUnbreakableItem,
    PriceForRepair,
    MapViewNotWorkingHere,
    HappyWithCharacter,
    YouDontKnowAnySpellsYet,
    EscapedTheTrap,
    CannotParry,
    InnkeeperGoodSleepWish,
    ItemCannotBeUsedHere,
    CannotCallEagleIfNotOnFoot,
    UseItOnWhom,
    NotInterestedInTrinket,
    NotAllowingToLookIntoBackpack,
    DontWantToTakeItemsWithYou,
    WaitingIsTooDangerous,
    AutomapperNotWorkingHere,
    GameOver,
    GameOverLoadOrQuit,
    NoSavegamesYetOnlyInitialGame,
    DontDeleteSavedGames,
    TurnOnTuneInAndDropOut,
    // Ambermoon Advanced
    ReviveCat = 338,
    CannotExchangeExpWithAnimals,
    CannotExchangeExpWithDead,
    ThisCantBeMoved,
    ElementNone,
    ElementMental,
    ElementSpirit,
    ElementPhysical,
    ElementUndead,
    ElementEarth,
    ElementWind,
    ElementFire,
    ElementWater,
    ElementMultiple,
    ElementLabel,
    SageIdentifyScroll,
    SageSLP,
    MountTheWasp,
    ImmuneToAttack,
    ExtendedLanguage1,
    ExtendedLanguage2,
    ExtendedLanguage3,
    ExtendedLanguage4,
    ExtendedLanguage5,
    ExtendedLanguage6,
    ExtendedLanguage7,
    ExtendedLanguage8,
    Count
}

