; Large buffers
; Reconstructed from the disassembly of AM2_CPU (Ambermoon 1.21).
; This part is missing in the original source code.


	SECTION	Buffer1_BSS,bss
Control_icons:
	ds.b	12168

	SECTION	Buffer2_BSS,bss
Item_data:
	ds.b	30000

	SECTION	Chip_BSS2,bss_c
Text_data:
	ds.l	1
	ds.b	2356
	ds.l	1
	ds.b	6208
	ds.w	11
	ds.b	4
	ds.w	1
	ds.b	2
	ds.l	1
	ds.w	2
	ds.b	636
	ds.w	2
	ds.b	396
	ds.l	2
	ds.b	24
	ds.w	2
	ds.l	2
	ds.b	12
	ds.w	10
	ds.b	572
	ds.w	3
	ds.b	2
	ds.l	1
	ds.b	13694
